### ISSUE TITLE
ModuleNotFoundError: No module named 'floris.tools.optimization.scipy'

### ISSUE THREAD

**Issue by YingyiLiu** [soanagno/wakeNet#1]
Dear developer of the WakeNet tool,

While I have properly installed Floris (which can be smoothly run), running the command "python -u example_main.py" of WakeNet reports the following error message:

Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File e:\github\wakenet\code\example_main.py:1
    from neuralWake import *

  File E:\GitHub\wakenet\Code\neuralWake.py:1
    from packages import *

  File E:\GitHub\wakenet\Code\packages.py:32
    from floris.tools.optimization.scipy.yaw import YawOptimization

ModuleNotFoundError: No module named 'floris.tools.optimization.scipy'

How can I fix this issue? Thanks.

**Comment by soanagno** [comment]
Hello,

Have you installed all the dependencies with their right versions?

Kind regards,
Sokratis

**Comment by YingyiLiu** [comment]
I installed all the other dependencies except the two following tools:
Dask (2021.10.0), optional
Cuda (11.3), optional

By the way, I installed the most recent Floris V3.3, other than V2.4. Perhaps Floris might be the reason?

Kind regards,
Yingyi

**Comment by soanagno** [comment]
Yes, the code was built using V2.4 of Floris.

Kind regards,
Sokratis
