### ISSUE TITLE
can't generate wake dataset using curl model

### ISSUE THREAD

**Issue by jiangshengkai1999** [soanagno/wakeNet#2]
I just change the inputs_curl.json and set the "train_net" to 1, and "make_data" to true, the outcome is  floris.tools.floris_interface.FlorisInterface INFO Model identified as curl requires use of underlying grid points
floris.tools.floris_interface.FlorisInterface INFO Assuming model resolution
floris.tools.floris_interface.FlorisInterface INFO      250      100       75
Nearest value to 90.00 is 87.65
and i can't solve this

**Comment by soanagno** [comment]
The Curl dataset was made using a modified version of FLORIS, since it was
not possible to tweak the dimensions in version 2.4.

**Comment by wangduo2001** [comment]
> The Curl dataset was made using a modified version of FLORIS, since it was not possible to tweak the dimensions in version 2.4.

Hello, may I ask where to get this modified version of FLORIS?  Thank you!
